---
- include:              '../tasks/install_packages.yml'
- include:              'configure_postfix.yml'
- include:              '../tasks/start_services.yml'
- include:              '../tasks/restart_services.yml'
  when:                 configure_postfix_result.changed
