---
- include_tasks:        '../tasks/install_packages.yml'
- include_tasks:        'configure_postfix.yml'
- include_tasks:        '../tasks/start_services.yml'
- include_tasks:        '../tasks/restart_services.yml'
  when:                 configure_postfix_result.changed
